export default [
	{ city: 'New York', state: 'New York', iata_code: 'NYC' },
	{ city: 'Charleston', state: 'South Carolina', iata_code: 'CHS' },
	{ city: 'Las Vegas', state: 'Nevada', iata_code: 'LAS' },
	{ city: 'Seattle', state: 'New York', iata_code: 'SEA' },
	{ city: 'Chicago', state: 'Illinois', iata_code: 'CHI' },
	{ city: 'San Francisco', state: 'California', iata_code: 'SFO' },
	{ city: 'Washington', state: 'DC', iata_code: 'IAD' },
	{ city: 'New Orleans', state: 'Louisiana', iata_code: 'MSY' },
	{ city: 'Orlando', state: 'Florida', iata_code: 'ORL' },
	{ city: 'Miami', state: 'Florida', iata_code: 'MIA' },
	{ city: 'Atlanta', state: 'Georgia', iata_code: 'ATL' },
	{ city: 'Los Angeles', state: 'California', iata_code: 'LAX' },
	{ city: 'San Diego', state: 'California', iata_code: 'SAN' },
	{ city: 'Philadelphia', state: 'Pennsylvania', iata_code: 'PHD' },
	{ city: 'Houston', state: 'Texas', iata_code: 'HOU' },
	{ city: 'Dallas', state: 'Texas', iata_code: 'DFW' },
	{ city: 'Denver', state: 'Colorado', iata_code: 'DEN' },
	{ city: 'Phoenix', state: 'Arizona', iata_code: 'PHX' },
	{ city: 'San Jose', state: 'California', iata_code: 'SJC' },
	{ city: 'Austin', state: 'Texas', iata_code: 'ASQ' },
	{ city: 'Jacksonville', state: 'Florida', iata_code: 'JAX' },
	{ city: 'Indianapolis', state: 'Indiana', iata_code: 'IND' },
	{ city: 'Columbus', state: 'Ohio', iata_code: 'OLU' },
	{ city: 'Charlotte', state: 'North Carolina', iata_code: 'CLT' },
	{ city: 'Detroit', state: 'Michigan', iata_code: 'DTT' },
	{ city: 'Memphis', state: 'Tennessee', iata_code: 'MEM' },
	{ city: 'Nashville', state: 'Tennessee', iata_code: 'BNA' },
	{ city: 'Baltimore', state: 'Maryland', iata_code: 'BWI' },
	{ city: 'Oklahoma City', state: 'Oklahoma', iata_code: 'OKC' },
	{ city: 'Portland', state: 'Oregon', iata_code: 'PDX' },
	{ city: 'Milwaukee', state: 'Wisconsin', iata_code: 'MKE' },
	{ city: 'Albuquerque', state: 'New Mexico', iata_code: 'ABQ' },
	{ city: 'Sacramento', state: 'California', iata_code: 'SAC' },
	{ city: 'Kansas City', state: 'Missouri', iata_code: 'MKC' },
	{ city: 'Omaha', state: 'Nebraska', iata_code: 'OMA' },
	{ city: 'Raleigh', state: 'North Carolina', iata_code: 'RDU' },
	{ city: 'Cleveland', state: 'Ohio', iata_code: 'CLE' }
];
