export default [
	// { city: 'New York', country: 'New York', iata_code: 'NYC' },
	// { city: 'Charleston', country: 'South Carolina', iata_code: 'CHS' },
	{ city: 'Las Vegas', country: 'Nevada', iata_code: 'LAS' },
	// { city: 'Seattle', country: 'New York', iata_code: 'SEA' },
	// { city: 'Chicago', country: 'Illinois', iata_code: 'CHI' },
	{ city: 'San Francisco', country: 'California', iata_code: 'SFO' },
	// { city: 'Washington', country: 'DC', iata_code: 'IAD' },
	// { city: 'New Orleans', country: 'Louisiana', iata_code: 'MSY' },
	// { city: 'Orlando', country: 'Florida', iata_code: 'ORL' },
	{ city: 'Miami', country: 'Florida', iata_code: 'MIA' },
	{ city: 'Atlanta', country: 'Georgia', iata_code: 'ATL' },
	{ city: 'Los Angeles', country: 'California', iata_code: 'LAX' },
	// { city: 'San Diego', country: 'California', iata_code: 'SAN' },
	// { city: 'Philadelphia', country: 'Pennsylvania', iata_code: 'PHD' },
	// { city: 'Houston', country: 'Texas', iata_code: 'HOU' },
	// { city: 'Dallas', country: 'Texas', iata_code: 'DFW' },
	// { city: 'Denver', country: 'Colorado', iata_code: 'DEN' },
	// { city: 'Phoenix', country: 'Arizona', iata_code: 'PHX' },
	// { city: 'San Jose', country: 'California', iata_code: 'SJC' },
	// { city: 'Austin', country: 'Texas', iata_code: 'ASQ' },
	// { city: 'Jacksonville', country: 'Florida', iata_code: 'JAX' },
	// { city: 'Indianapolis', country: 'Indiana', iata_code: 'IND' },
	// { city: 'Columbus', country: 'Ohio', iata_code: 'OLU' },
	// { city: 'Charlotte', country: 'North Carolina', iata_code: 'CLT' },
	// { city: 'Detroit', country: 'Michigan', iata_code: 'DTT' },
	// { city: 'Memphis', country: 'Tennessee', iata_code: 'MEM' },
	// { city: 'Nashville', country: 'Tennessee', iata_code: 'BNA' },
	// { city: 'Baltimore', country: 'Maryland', iata_code: 'BWI' },
	// { city: 'Oklahoma City', country: 'Oklahoma', iata_code: 'OKC' },
	// { city: 'Portland', country: 'Oregon', iata_code: 'PDX' },
	// { city: 'Milwaukee', country: 'Wisconsin', iata_code: 'MKE' },
	// { city: 'Albuquerque', country: 'New Mexico', iata_code: 'ABQ' },
	// { city: 'Sacramento', country: 'California', iata_code: 'SAC' },
	// { city: 'Kansas City', country: 'Missouri', iata_code: 'MKC' },
	// { city: 'Omaha', country: 'Nebraska', iata_code: 'OMA' },
	// { city: 'Raleigh', country: 'North Carolina', iata_code: 'RDU' },
	// { city: 'Cleveland', country: 'Ohio', iata_code: 'CLE' },
	// { city: 'Madrid', country: 'Spain', iata_code: 'MAD' },
];
